// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SchemaInput struct {
	ServiceName string `json:"serviceName"`
	ServiceURL  string `json:"serviceUrl"`
	TypeDefs    string `json:"typeDefs"`
}
